filebeat.config:
  # modules:
  #   path: ${path.config}/modules.d/*.yml
  #   reload.enabled: false

# logging.level: debug
filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/haproxy/access.log
    ignore_older: 24h
    # tags: ["back"]
    # fields:
    #   env: prod
    #   owner: rui

# filebeat.autodiscover:
#   providers:
#     - type: docker
#       hints.enabled: true

# processors:
#   - drop_fields:
#       fields: ["haproxy.http.request.captured_headers"]
# processors:
#   - drop_fields:
#       fields: ["message", "haproxy.bytes_read"]
#       ignore_missing: true
#   - add_cloud_metadata: ~
#   - dissect:
#       tokenizer: "%{key1} %{key2} %{key3|convert_datatype}"
#       field: "message"
#       target_prefix: "dissect"

# output.elasticsearch:
#   hosts: "elasticsearch:9200"

output.logstash:
  hosts: "logstash:5044"

setup.kibana:
  host: "kibana:5601"
